name: Greeting data academy

on:
  push
    

env:
  DAY_OF_WEEK: Monday
  

jobs:
  # greeting_job:
  #   runs-on: self-hosted
  #   env:
  #     GREETING: Hello
  #   steps:
  #     - name: "Say 'Hello Data Academy 7th edition, this is <today's weekday> 's first exercise! I'm <MY_NAME>!'"
  #       run: echo "$GREETING $ACADEMY_TYPE Academy 7th edition, this is $DAY_OF_WEEK's first exercise! I'm $GITHUB_ACTOR!"
  #       env:
  #         ACADEMY_TYPE: Data


  # checkov-job:
  #   runs-on: self-hosted
  #   name: checkov-action
  #   permissions:
  #     contents: read # for actions/checkout to fetch code
  #     security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
  #     actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@master

  #     - name: Run Checkov action
  #       id: checkov
  #       uses: bridgecrewio/checkov-action@master
  #       with:
  #         directory: 02_devops_fundamentals/ci_cd/terraform-exercise-3a/
  #         soft_fail: true # optional: do not return an error code if there are failed checks
  #         # framework: terraform # optional: run only on a specific infrastructure {cloudformation,terraform,kubernetes,all}
  #         # output_file_path: reports/results.sarif # folder and name of results file

  unit_tests:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pytest pytest-cov
      
      - name: Run pytest
        run: pytest 02_devops_fundamentals/ci_cd/terraform-exercise-3/unittests/test.py --cov


  

