name: Greeting data academy

on:
  push:
    branches: [main]

env:
  DAY_OF_WEEK: Monday

jobs:
  week_job:
    runs-on: self-hosted
    needs: greeting_job
    env:
      WHAT: pancakes
      WITH: chocolate
      
    steps:
      - name: "week job"
      run: echo "I like $WHAT with $WITH!"

  greeting_job:
    runs-on: self-hosted
    env:
      GREETING: Hello
    steps:
      - name: "Say 'Hello Data Academy 7th edition, this is <today's weekday> 's first exercise! I'm <MY_NAME>!'"
        run: echo "$GREETING $ACADEMY_TYPE Academy 7th edition, this is $DAY_OF_WEEK's first exercise! I'm $GITHUB_ACTOR!"
        env:
          ACADEMY_TYPE: Data

