name: Greeting data academy

on:
  push:
    branches-ignore: [main]

jobs:

  terraform:
    needs:
      - greeting_job
    steps:
      #Required to setup terraform
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "16"

      - name: Checkout Repo
        uses: #TODO

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.9

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: #TODO
          aws-secret-access-key: #TODO
          aws-session-token: #TODO
          aws-region: eu-central-1

      - name: Terraform Init
        run: |
          cd 02_devops_fundamentals/ci_cd/terraform-exercise-1
          #TODO

      - name: Terraform Plan
        run: |
          cd 02_devops_fundamentals/ci_cd/terraform-exercise-1
          #TODO

      - name: Terraform Apply
        run: |
          cd 02_devops_fundamentals/ci_cd/terraform-exercise-1
          #TODO